'use client';
import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type BuilderSection = 'Identity' | 'Description' | 'Purpose' | 'Personality' | 'Language' | 'Behavior Rules' | 'Knowledge' | 'Tools' | 'Transfers' | 'Output Format';
export type AgentBuilderConfig = { sections: Record<BuilderSection, string>; voice: string; pace: string; interruptionSensitivity: string };
const defaultConfig: AgentBuilderConfig = { sections: { Identity: 'You are Avery, a helpful sales development agent for Acme Healthcare.', Description: 'A concise overview of what this agent is responsible for.', Purpose: 'Qualify inbound leads and schedule a discovery call when there is a fit.', Personality: 'Warm, precise, and professionally curious.', Language: 'Speak English (US) by default. Match the caller when supported.', 'Behavior Rules': 'Be concise, confirm important details, and never make unsupported claims.', Knowledge: 'Use the selected workspace sources. Never invent product details.', Tools: 'Use calendar availability only after a qualified caller asks to book.', Transfers: 'Transfer billing questions to the Billing queue with a short summary.', 'Output Format': 'Capture qualified lead details in the specified structured fields.' }, voice: 'Nova - Clear and warm', pace: 'Natural', interruptionSensitivity: 'Balanced' };
type BuilderState = { config: AgentBuilderConfig; savedConfig: AgentBuilderConfig; updateSection: (section: BuilderSection, value: string) => void; updateSetting: (setting: 'voice'|'pace'|'interruptionSensitivity', value: string) => void; save: () => void; discard: () => void; hasUnsavedChanges: () => boolean };
export const useAgentBuilderStore = create<BuilderState>()(persist((set, get) => ({ config: defaultConfig, savedConfig: defaultConfig, updateSection: (section, value) => set((state) => ({ config: { ...state.config, sections: { ...state.config.sections, [section]: value } } })), updateSetting: (setting, value) => set((state) => ({ config: { ...state.config, [setting]: value } })), save: () => set((state) => ({ savedConfig: structuredClone(state.config) })), discard: () => set((state) => ({ config: structuredClone(state.savedConfig) })), hasUnsavedChanges: () => JSON.stringify(get().config) !== JSON.stringify(get().savedConfig) }), { name: 'relay-agent-builder-a1' }));
